// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGKNA3FlujO-krD33PSLsI-EMDWqc-KNw',
    appId: '1:1006017796784:web:1cd5a6a800f1e9d30cb975',
    messagingSenderId: '1006017796784',
    projectId: 'portfolio-message-4f3be',
    authDomain: 'portfolio-message-4f3be.firebaseapp.com',
    storageBucket: 'portfolio-message-4f3be.firebasestorage.app',
    measurementId: 'G-C19VXKLWRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9OiZzI_5zpkI4xCF_oJun1sDIxkoh2dQ',
    appId: '1:1006017796784:android:88a943f616903a880cb975',
    messagingSenderId: '1006017796784',
    projectId: 'portfolio-message-4f3be',
    storageBucket: 'portfolio-message-4f3be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6P-zpNFZwBPup2DKM7oKYM4kXW5fVcHc',
    appId: '1:1006017796784:ios:13b0b6ab95aaac640cb975',
    messagingSenderId: '1006017796784',
    projectId: 'portfolio-message-4f3be',
    storageBucket: 'portfolio-message-4f3be.firebasestorage.app',
    iosBundleId: 'com.example.portfolioMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6P-zpNFZwBPup2DKM7oKYM4kXW5fVcHc',
    appId: '1:1006017796784:ios:13b0b6ab95aaac640cb975',
    messagingSenderId: '1006017796784',
    projectId: 'portfolio-message-4f3be',
    storageBucket: 'portfolio-message-4f3be.firebasestorage.app',
    iosBundleId: 'com.example.portfolioMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGKNA3FlujO-krD33PSLsI-EMDWqc-KNw',
    appId: '1:1006017796784:web:ec98e533e7503e9c0cb975',
    messagingSenderId: '1006017796784',
    projectId: 'portfolio-message-4f3be',
    authDomain: 'portfolio-message-4f3be.firebaseapp.com',
    storageBucket: 'portfolio-message-4f3be.firebasestorage.app',
    measurementId: 'G-T6EM5W4EZM',
  );
}
